version: "3.8"
services:
  api1:
    build: .
    ports:
      - "9999:9999"
    environment:
      INDEX_PATH: "/app/resources/index.bin"
      MCC_RISK_PATH: "/app/resources/mcc_risk.json"
      LISTEN_TCP: "1"
      PORT: "9999"
      HOST: "0.0.0.0"
      IVF_NPROBE: "1"
      CANDIDATES: "0"
      AMOUNT_DIVISOR: "10000"
      INSTALLMENTS_DIVISOR: "12"
      TX24H_DIVISOR: "20"
      KM_DIVISOR: "1000"
      MERCHANT_AMOUNT_DIVISOR: "10000"
      GOGC: "200"
      GOMEMLIMIT: "100MiB"
    cpus: "0.80"
    mem_limit: "150MB"
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "150MB"
