x-api-common: &api-common
  image: ghcr.io/macedot/rinha-2026-zig:latest
  volumes:
    - rinha-zig-sockets:/sockets
  networks:
    - rinha-zig-net
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "160M"
  environment: &api-env
    INDEX_PATH: "/app/resources/index.bin"
    LISTEN_TCP: "0"
    UDS_MODE: "666"
    UNLINK_UDS: "1"
    IVF_NPROBE: "8"
    IVF_FULL_NPROBE: "24"
    CANDIDATES: "0"

services:
  passa:
    image: ghcr.io/macedot/passa:latest
    container_name: rinha-zig-passa
    ports:
      - "9999:9999"
    volumes:
      - rinha-zig-sockets:/sockets
    depends_on:
      - api1
      - api2
    networks:
      - rinha-zig-net
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50M"
    environment:
      PORT: "9999"
      BUF_SIZE: "4096"
      UPSTREAMS: "/sockets/api1.sock,/sockets/api2.sock"

  api1:
    <<: *api-common
    container_name: rinha-zig-api1
    hostname: api1
    environment:
      <<: *api-env
      UDS_PATH: "/sockets/api1.sock"

  api2:
    <<: *api-common
    container_name: rinha-zig-api2
    hostname: api2
    environment:
      <<: *api-env
      UDS_PATH: "/sockets/api2.sock"

networks:
  rinha-zig-net:
    driver: bridge

volumes:
  rinha-zig-sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
