x-api-common: &api-common
  build: .
  volumes:
    - rinha-sockets:/sockets
  networks:
    - rinha-net
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  deploy:
    resources:
      limits:
        cpus: "0.425"
        memory: "150MB"
  environment: &api-env
    INDEX_PATH: "/app/resources/index.bin"
    MCC_RISK_PATH: "/app/resources/mcc_risk.json"
    LISTEN_TCP: "0"
    UDS_MODE: "666"
    UNLINK_UDS: "1"
    IVF_NPROBE: "4"
    IVF_FULL_NPROBE: "4"
    CANDIDATES: "0"
    AMOUNT_DIVISOR: "10000"
    INSTALLMENTS_DIVISOR: "12"
    TX24H_DIVISOR: "20"
    KM_DIVISOR: "1000"
    MERCHANT_AMOUNT_DIVISOR: "10000"
    GOGC: "100"
    GOMEMLIMIT: "100MiB"

services:
  haproxy:
    image: haproxy:3.3
    container_name: rinha-haproxy
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - rinha-sockets:/sockets
    depends_on:
      - api1
      - api2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"

  api1:
    <<: *api-common
    container_name: rinha-api1
    hostname: api1
    environment:
      <<: *api-env
      UDS_PATH: "/sockets/api1.sock"

  api2:
    <<: *api-common
    container_name: rinha-api2
    hostname: api2
    environment:
      <<: *api-env
      UDS_PATH: "/sockets/api2.sock"

networks:
  rinha-net:
    driver: bridge

volumes:
  rinha-sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
